In [15]:
import pandas as pd

In [92]:
#sheets=pd.read_excel('2. Manufacturing.xlsx', sheet_name=['Tata Chemicals','Reliance Power'])
sheet_tatachem=pd.read_excel('2. Manufacturing.xlsx', sheet_name=['Tata Chemicals'])
sheet_relpow=pd.read_excel('2. Manufacturing.xlsx', sheet_name=['Reliance Power'])

In [93]:
sheet_tatachem

OrderedDict([('Tata Chemicals',
                 Key Financial Ratios of Tata Chemicals  Unnamed: 1  Unnamed: 2  Unnamed: 3  \
              0                                     NaN         NaN         NaN         NaN
              1                                     NaN         NaN         NaN         NaN
              2                                     NaN     2007.00     2008.00     2009.00
              3                    Profitability Ratios         NaN         NaN         NaN
              4                        PBDIT Margin (%)       20.52       32.42       11.33
              5                         PBIT Margin (%)       16.71       28.73        9.38
              6                          PBT Margin (%)       15.63       28.21        7.64
              7                   Net Profit Margin (%)       11.25       23.51        5.40
              8         Return on Networth / Equity (%)       18.56       26.57       12.48
              9          Return on Capital Employed (%)       13.08       22.61       10.07
              10                   Return on Assets (%)        9.28       12.58        4.61
              11                        Basic EPS (Rs.)       20.65       40.56       19.22
              12                      Diluted EPS (Rs.)       20.65       40.56       19.22
              13                         Cash EPS (Rs.)       27.63       46.92       26.15
              14                                    NaN         NaN         NaN         NaN
              15                        Leverage Ratios         NaN         NaN         NaN
              16                  Total Debt/Equity (X)        0.44        0.66        1.01
              17                                    NaN         NaN         NaN         NaN
              18                                    NaN         NaN         NaN         NaN
              19                       Liquidity Ratios         NaN         NaN         NaN
              20                      Current Ratio (X)        1.36        0.68        0.62
              21                        Quick Ratio (X)        1.00        0.48        0.44
              22                                    NaN         NaN         NaN         NaN
              23                      Efficiency Ratios         NaN         NaN         NaN
              24           Inventory Turnover Ratio (X)        7.79        6.14        8.62
              25         Dividend Payout Ratio (NP) (%)       38.73       22.25       46.82
              26         Dividend Payout Ratio (CP) (%)       28.94       19.24       34.41
              27           Earnings Retention Ratio (%)       61.27       77.75       53.18
              28      Cash Earnings Retention Ratio (%)       71.06       80.76       65.59
              29               Asset Turnover Ratio (%)       82.47       53.51       85.41
              30                                    NaN         NaN         NaN         NaN
              31                       Valuation Ratios         NaN         NaN         NaN
              32                 Enterprise Value (Cr.)     5400.03     8638.37     6359.97
              33           EV/Net Operating Revenue (X)        1.37        2.14        0.76
              34                          EV/EBITDA (X)        6.67        6.60        6.71
              35    MarketCap/Net Operating Revenue (X)        1.13        1.63        0.40
              36                   Retention Ratios (%)       61.26       77.74       53.17
              37                           Price/BV (X)        1.86        1.84        0.92
              38            Price/Net Operating Revenue        1.13        1.63        0.40
              39                         Earnings Yield        0.10        0.14        0.14
              40                                    NaN         NaN         NaN         NaN

                 Unnamed: 4           Unnamed: 5  Unnamed: 6  Unnamed: 7  Unnamed: 8  \
              0         NaN                  NaN         NaN         NaN         NaN
              1         NaN                  NaN         NaN         NaN         NaN
              2    Pre-Mean  2017-03-10 00:00:00     2011.00     2012.00     2013.00
              3         NaN                  NaN         NaN         NaN         NaN
              4     21.4233                17.46       15.81       16.66       16.55
              5     18.2733                   14       12.58       13.85       14.04
              6       17.16                10.49        8.82        9.55        9.67
              7     13.3867                 8.03        6.45        7.33        7.54
              8     19.2033                10.17        8.61       11.88       12.12
              9     15.2533                 8.21        5.37        7.92        9.60
              10    8.82333                 4.81        4.30        5.43        5.79
              11      26.81                17.87       16.32       23.03       25.25
              12      26.81                17.87       16.32       23.03       25.25
              13    33.5667                25.56       24.05       31.84       33.66
              14     20.071                  NaN         NaN         NaN         NaN
              15        NaN                  NaN         NaN         NaN         NaN
              16   0.703333                 0.69        0.57        0.50        0.46
              17        NaN                  NaN         NaN         NaN         NaN
              18        NaN                  NaN         NaN         NaN         NaN
              19        NaN                  NaN         NaN         NaN         NaN
              20   0.886667                 0.58        1.32        1.15        1.10
              21       0.64                 0.42        0.95        0.78        0.88
              22   0.763333                  NaN         NaN         NaN         NaN
              23        NaN                  NaN         NaN         NaN         NaN
              24    7.51667                 8.85        9.10        6.38        9.20
              25    35.9333                50.35       62.36       43.42       39.60
              26      27.53                35.19       41.56       31.40       29.70
              27    64.0667                49.65       37.64       56.58       60.40
              28      72.47                64.81       58.44       68.60       70.30
              29    73.7967                59.91       66.69       74.08       76.85
              30    46.8856                  NaN         NaN         NaN         NaN
              31        NaN                  NaN         NaN         NaN         NaN
              32    6799.46              10186.8    10532.26    10372.89     9580.48
              33    1.42333                 1.88        1.66        1.30        1.12
              34       6.66                10.78       10.52        7.79        6.79
              35    1.05333                 1.47        1.36        1.10        0.96
              36    64.0567                49.64       37.63       56.57       60.39
              37       1.54                 1.86        1.82        1.78        1.55
              38    1.05333                 1.47        1.36        1.10        0.96
              39   0.126667                 0.05        0.05        0.07        0.08
              40    859.421                  NaN         NaN         NaN         NaN

                 Unnamed: 9  Unnamed: 10  Unnamed: 11  Unnamed: 12  Unnamed: 13  \
              0         NaN          NaN          NaN          NaN          NaN
              1         NaN          NaN          NaN          NaN          NaN
              2   Post-Mean          NaN          NaN          NaN          NaN
              3         NaN          NaN          NaN          NaN          NaN
              4       16.34          NaN          NaN          NaN          NaN
              5       13.49          NaN          NaN          NaN          NaN
              6     9.34667          NaN          NaN          NaN          NaN
              7     7.10667          NaN          NaN          NaN          NaN
              8       10.87          NaN          NaN          NaN          NaN
              9        7.63          NaN          NaN          NaN          NaN
              10    5.17333          NaN          NaN          NaN          NaN
              11    21.5333          NaN          NaN          NaN          NaN
              12    21.5333          NaN          NaN          NaN          NaN
              13      29.85          NaN          NaN          NaN          NaN
              14    14.2873          NaN          NaN          NaN          NaN
              15        NaN          NaN          NaN          NaN          NaN
              16       0.51          NaN          NaN          NaN          NaN
              17        NaN          NaN          NaN          NaN          NaN
              18        NaN          NaN          NaN          NaN          NaN
              19        NaN          NaN          NaN          NaN          NaN
              20       1.19          NaN          NaN          NaN          NaN
              21       0.87          NaN          NaN          NaN          NaN
              22       1.03          NaN          NaN          NaN          NaN
              23        NaN          NaN          NaN          NaN          NaN
              24    8.22667          NaN          NaN          NaN          NaN
              25      48.46          NaN          NaN          NaN          NaN
              26      34.22          NaN          NaN          NaN          NaN
              27      51.54          NaN          NaN          NaN          NaN
              28      65.78          NaN          NaN          NaN          NaN
              29      72.54          NaN          NaN          NaN          NaN
              30    46.7944          NaN          NaN          NaN          NaN
              31        NaN          NaN          NaN          NaN          NaN
              32    10161.9          NaN          NaN          NaN          NaN
              33       1.36          NaN          NaN          NaN          NaN
              34    8.36667          NaN          NaN          NaN          NaN
              35       1.14          NaN          NaN          NaN          NaN
              36      51.53          NaN          NaN          NaN          NaN
              37    1.71667          NaN          NaN          NaN          NaN
              38       1.14          NaN          NaN          NaN          NaN
              39  0.0666667          NaN          NaN          NaN          NaN
              40     1278.4          NaN          NaN          NaN          NaN

                  Unnamed: 14  Unnamed: 15  Unnamed: 16  Unnamed: 17  Unnamed: 18  \
              0           NaN          NaN          NaN          NaN          NaN
              1           NaN          NaN          NaN          NaN          NaN
              2           NaN          NaN          NaN          NaN          NaN
              3           NaN          NaN          NaN          NaN          NaN
              4           NaN          NaN          NaN          NaN          NaN
              5           NaN          NaN          NaN          NaN          NaN
              6           NaN          NaN          NaN          NaN          NaN
              7           NaN          NaN          NaN          NaN          NaN
              8           NaN          NaN          NaN          NaN          NaN
              9           NaN          NaN          NaN          NaN          NaN
              10          NaN          NaN          NaN          NaN          NaN
              11          NaN          NaN          NaN          NaN          NaN
              12          NaN          NaN          NaN          NaN          NaN
              13          NaN          NaN          NaN          NaN          NaN
              14          NaN          NaN          NaN          NaN          NaN
              15          NaN          NaN          NaN          NaN          NaN
              16          NaN          NaN          NaN          NaN          NaN
              17          NaN          NaN          NaN          NaN          NaN
              18          NaN          NaN          NaN          NaN          NaN
              19          NaN          NaN          NaN          NaN          NaN
              20          NaN          NaN          NaN          NaN          NaN
              21          NaN          NaN          NaN          NaN          NaN
              22          NaN          NaN          NaN          NaN          NaN
              23          NaN          NaN          NaN          NaN          NaN
              24          NaN          NaN          NaN          NaN          NaN
              25          NaN          NaN          NaN          NaN          NaN
              26          NaN          NaN          NaN          NaN          NaN
              27          NaN          NaN          NaN          NaN          NaN
              28          NaN          NaN          NaN          NaN          NaN
              29          NaN          NaN          NaN          NaN          NaN
              30          NaN          NaN          NaN          NaN          NaN
              31          NaN          NaN          NaN          NaN          NaN
              32          NaN          NaN          NaN          NaN          NaN
              33          NaN          NaN          NaN          NaN          NaN
              34          NaN          NaN          NaN          NaN          NaN
              35          NaN          NaN          NaN          NaN          NaN
              36          NaN          NaN          NaN          NaN          NaN
              37          NaN          NaN          NaN          NaN          NaN
              38          NaN          NaN          NaN          NaN          NaN
              39          NaN          NaN          NaN          NaN          NaN
              40          NaN          NaN          NaN          NaN          NaN

                  Unnamed: 19
              0           NaN
              1           NaN
              2           NaN
              3           NaN
              4           NaN
              5           NaN
              6           NaN
              7           NaN
              8           NaN
              9           NaN
              10          NaN
              11          NaN
              12          NaN
              13          NaN
              14          NaN
              15          NaN
              16          NaN
              17          NaN
              18          NaN
              19          NaN
              20          NaN
              21          NaN
              22          NaN
              23          NaN
              24          NaN
              25          NaN
              26          NaN
              27          NaN
              28          NaN
              29          NaN
              30          NaN
              31          NaN
              32          NaN
              33          NaN
              34          NaN
              35          NaN
              36          NaN
              37          NaN
              38          NaN
              39          NaN
              40          NaN  )])

In [83]:
sheets_dict=pd.read_excel('2. Manufacturing.xlsx', sheet_name=None)

In [91]:
full_table = pd.DataFrame()
for name, sheet in sheets_dict.items():
    sheet['sheet'] = name
    sheet = sheet.rename(columns=lambda x: x.split('\n')[-1])
    full_table = full_table.append(sheet)

full_table.reset_index(inplace=True, drop=True)

full_table.columns
full_table.to_excel(r'fulldata.xlsx')

In [70]:
for key, value in sheet_tatachem.items() 
    print(key,value)

AttributeError: 'odict_items' object has no attribute 'key'

In [77]:
sheet_tatachem.items().

odict_items([('Tata Chemicals',    Key Financial Ratios of Tata Chemicals  Unnamed: 1  Unnamed: 2  Unnamed: 3  \
0                                     NaN         NaN         NaN         NaN
1                                     NaN         NaN         NaN         NaN
2                                     NaN     2007.00     2008.00     2009.00
3                    Profitability Ratios         NaN         NaN         NaN
4                        PBDIT Margin (%)       20.52       32.42       11.33
5                         PBIT Margin (%)       16.71       28.73        9.38
6                          PBT Margin (%)       15.63       28.21        7.64
7                   Net Profit Margin (%)       11.25       23.51        5.40
8         Return on Networth / Equity (%)       18.56       26.57       12.48
9          Return on Capital Employed (%)       13.08       22.61       10.07
10                   Return on Assets (%)        9.28       12.58        4.61
11                        Basic EPS (Rs.)       20.65       40.56       19.22
12                      Diluted EPS (Rs.)       20.65       40.56       19.22
13                         Cash EPS (Rs.)       27.63       46.92       26.15
14                                    NaN         NaN         NaN         NaN
15                        Leverage Ratios         NaN         NaN         NaN
16                  Total Debt/Equity (X)        0.44        0.66        1.01
17                                    NaN         NaN         NaN         NaN
18                                    NaN         NaN         NaN         NaN
19                       Liquidity Ratios         NaN         NaN         NaN
20                      Current Ratio (X)        1.36        0.68        0.62
21                        Quick Ratio (X)        1.00        0.48        0.44
22                                    NaN         NaN         NaN         NaN
23                      Efficiency Ratios         NaN         NaN         NaN
24           Inventory Turnover Ratio (X)        7.79        6.14        8.62
25         Dividend Payout Ratio (NP) (%)       38.73       22.25       46.82
26         Dividend Payout Ratio (CP) (%)       28.94       19.24       34.41
27           Earnings Retention Ratio (%)       61.27       77.75       53.18
28      Cash Earnings Retention Ratio (%)       71.06       80.76       65.59
29               Asset Turnover Ratio (%)       82.47       53.51       85.41
30                                    NaN         NaN         NaN         NaN
31                       Valuation Ratios         NaN         NaN         NaN
32                 Enterprise Value (Cr.)     5400.03     8638.37     6359.97
33           EV/Net Operating Revenue (X)        1.37        2.14        0.76
34                          EV/EBITDA (X)        6.67        6.60        6.71
35    MarketCap/Net Operating Revenue (X)        1.13        1.63        0.40
36                   Retention Ratios (%)       61.26       77.74       53.17
37                           Price/BV (X)        1.86        1.84        0.92
38            Price/Net Operating Revenue        1.13        1.63        0.40
39                         Earnings Yield        0.10        0.14        0.14
40                                    NaN         NaN         NaN         NaN

   Unnamed: 4           Unnamed: 5  Unnamed: 6  Unnamed: 7  Unnamed: 8  \
0         NaN                  NaN         NaN         NaN         NaN
1         NaN                  NaN         NaN         NaN         NaN
2    Pre-Mean  2017-03-10 00:00:00     2011.00     2012.00     2013.00
3         NaN                  NaN         NaN         NaN         NaN
4     21.4233                17.46       15.81       16.66       16.55
5     18.2733                   14       12.58       13.85       14.04
6       17.16                10.49        8.82        9.55        9.67
7     13.3867                 8.03        6.45        7.33        7.54
8     19.2033                10.17        8.61       11.88       12.12
9     15.2533                 8.21        5.37        7.92        9.60
10    8.82333                 4.81        4.30        5.43        5.79
11      26.81                17.87       16.32       23.03       25.25
12      26.81                17.87       16.32       23.03       25.25
13    33.5667                25.56       24.05       31.84       33.66
14     20.071                  NaN         NaN         NaN         NaN
15        NaN                  NaN         NaN         NaN         NaN
16   0.703333                 0.69        0.57        0.50        0.46
17        NaN                  NaN         NaN         NaN         NaN
18        NaN                  NaN         NaN         NaN         NaN
19        NaN                  NaN         NaN         NaN         NaN
20   0.886667                 0.58        1.32        1.15        1.10
21       0.64                 0.42        0.95        0.78        0.88
22   0.763333                  NaN         NaN         NaN         NaN
23        NaN                  NaN         NaN         NaN         NaN
24    7.51667                 8.85        9.10        6.38        9.20
25    35.9333                50.35       62.36       43.42       39.60
26      27.53                35.19       41.56       31.40       29.70
27    64.0667                49.65       37.64       56.58       60.40
28      72.47                64.81       58.44       68.60       70.30
29    73.7967                59.91       66.69       74.08       76.85
30    46.8856                  NaN         NaN         NaN         NaN
31        NaN                  NaN         NaN         NaN         NaN
32    6799.46              10186.8    10532.26    10372.89     9580.48
33    1.42333                 1.88        1.66        1.30        1.12
34       6.66                10.78       10.52        7.79        6.79
35    1.05333                 1.47        1.36        1.10        0.96
36    64.0567                49.64       37.63       56.57       60.39
37       1.54                 1.86        1.82        1.78        1.55
38    1.05333                 1.47        1.36        1.10        0.96
39   0.126667                 0.05        0.05        0.07        0.08
40    859.421                  NaN         NaN         NaN         NaN

   Unnamed: 9  Unnamed: 10  Unnamed: 11  Unnamed: 12  Unnamed: 13  \
0         NaN          NaN          NaN          NaN          NaN
1         NaN          NaN          NaN          NaN          NaN
2   Post-Mean          NaN          NaN          NaN          NaN
3         NaN          NaN          NaN          NaN          NaN
4       16.34          NaN          NaN          NaN          NaN
5       13.49          NaN          NaN          NaN          NaN
6     9.34667          NaN          NaN          NaN          NaN
7     7.10667          NaN          NaN          NaN          NaN
8       10.87          NaN          NaN          NaN          NaN
9        7.63          NaN          NaN          NaN          NaN
10    5.17333          NaN          NaN          NaN          NaN
11    21.5333          NaN          NaN          NaN          NaN
12    21.5333          NaN          NaN          NaN          NaN
13      29.85          NaN          NaN          NaN          NaN
14    14.2873          NaN          NaN          NaN          NaN
15        NaN          NaN          NaN          NaN          NaN
16       0.51          NaN          NaN          NaN          NaN
17        NaN          NaN          NaN          NaN          NaN
18        NaN          NaN          NaN          NaN          NaN
19        NaN          NaN          NaN          NaN          NaN
20       1.19          NaN          NaN          NaN          NaN
21       0.87          NaN          NaN          NaN          NaN
22       1.03          NaN          NaN          NaN          NaN
23        NaN          NaN          NaN          NaN          NaN
24    8.22667          NaN          NaN          NaN          NaN
25      48.46          NaN          NaN          NaN          NaN
26      34.22          NaN          NaN          NaN          NaN
27      51.54          NaN          NaN          NaN          NaN
28      65.78          NaN          NaN          NaN          NaN
29      72.54          NaN          NaN          NaN          NaN
30    46.7944          NaN          NaN          NaN          NaN
31        NaN          NaN          NaN          NaN          NaN
32    10161.9          NaN          NaN          NaN          NaN
33       1.36          NaN          NaN          NaN          NaN
34    8.36667          NaN          NaN          NaN          NaN
35       1.14          NaN          NaN          NaN          NaN
36      51.53          NaN          NaN          NaN          NaN
37    1.71667          NaN          NaN          NaN          NaN
38       1.14          NaN          NaN          NaN          NaN
39  0.0666667          NaN          NaN          NaN          NaN
40     1278.4          NaN          NaN          NaN          NaN

    Unnamed: 14  Unnamed: 15  Unnamed: 16  Unnamed: 17  Unnamed: 18  \
0           NaN          NaN          NaN          NaN          NaN
1           NaN          NaN          NaN          NaN          NaN
2           NaN          NaN          NaN          NaN          NaN
3           NaN          NaN          NaN          NaN          NaN
4           NaN          NaN          NaN          NaN          NaN
5           NaN          NaN          NaN          NaN          NaN
6           NaN          NaN          NaN          NaN          NaN
7           NaN          NaN          NaN          NaN          NaN
8           NaN          NaN          NaN          NaN          NaN
9           NaN          NaN          NaN          NaN          NaN
10          NaN          NaN          NaN          NaN          NaN
11          NaN          NaN          NaN          NaN          NaN
12          NaN          NaN          NaN          NaN          NaN
13          NaN          NaN          NaN          NaN          NaN
14          NaN          NaN          NaN          NaN          NaN
15          NaN          NaN          NaN          NaN          NaN
16          NaN          NaN          NaN          NaN          NaN
17          NaN          NaN          NaN          NaN          NaN
18          NaN          NaN          NaN          NaN          NaN
19          NaN          NaN          NaN          NaN          NaN
20          NaN          NaN          NaN          NaN          NaN
21          NaN          NaN          NaN          NaN          NaN
22          NaN          NaN          NaN          NaN          NaN
23          NaN          NaN          NaN          NaN          NaN
24          NaN          NaN          NaN          NaN          NaN
25          NaN          NaN          NaN          NaN          NaN
26          NaN          NaN          NaN          NaN          NaN
27          NaN          NaN          NaN          NaN          NaN
28          NaN          NaN          NaN          NaN          NaN
29          NaN          NaN          NaN          NaN          NaN
30          NaN          NaN          NaN          NaN          NaN
31          NaN          NaN          NaN          NaN          NaN
32          NaN          NaN          NaN          NaN          NaN
33          NaN          NaN          NaN          NaN          NaN
34          NaN          NaN          NaN          NaN          NaN
35          NaN          NaN          NaN          NaN          NaN
36          NaN          NaN          NaN          NaN          NaN
37          NaN          NaN          NaN          NaN          NaN
38          NaN          NaN          NaN          NaN          NaN
39          NaN          NaN          NaN          NaN          NaN
40          NaN          NaN          NaN          NaN          NaN

    Unnamed: 19
0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
5           NaN
6           NaN
7           NaN
8           NaN
9           NaN
10          NaN
11          NaN
12          NaN
13          NaN
14          NaN
15          NaN
16          NaN
17          NaN
18          NaN
19          NaN
20          NaN
21          NaN
22          NaN
23          NaN
24          NaN
25          NaN
26          NaN
27          NaN
28          NaN
29          NaN
30          NaN
31          NaN
32          NaN
33          NaN
34          NaN
35          NaN
36          NaN
37          NaN
38          NaN
39          NaN
40          NaN  )])

In [32]:
sheet_tatachem, sheet_relpow

(OrderedDict([('Tata Chemicals',
                  Key Financial Ratios of Tata Chemicals  Unnamed: 1  Unnamed: 2  Unnamed: 3  \
               0                                     NaN         NaN         NaN         NaN
               1                                     NaN         NaN         NaN         NaN
               2                                     NaN     2007.00     2008.00     2009.00
               3                    Profitability Ratios         NaN         NaN         NaN
               4                        PBDIT Margin (%)       20.52       32.42       11.33
               5                         PBIT Margin (%)       16.71       28.73        9.38
               6                          PBT Margin (%)       15.63       28.21        7.64
               7                   Net Profit Margin (%)       11.25       23.51        5.40
               8         Return on Networth / Equity (%)       18.56       26.57       12.48
               9          Return on Capital Employed (%)       13.08       22.61       10.07
               10                   Return on Assets (%)        9.28       12.58        4.61
               11                        Basic EPS (Rs.)       20.65       40.56       19.22
               12                      Diluted EPS (Rs.)       20.65       40.56       19.22
               13                         Cash EPS (Rs.)       27.63       46.92       26.15
               14                                    NaN         NaN         NaN         NaN
               15                        Leverage Ratios         NaN         NaN         NaN
               16                  Total Debt/Equity (X)        0.44        0.66        1.01
               17                                    NaN         NaN         NaN         NaN
               18                                    NaN         NaN         NaN         NaN
               19                       Liquidity Ratios         NaN         NaN         NaN
               20                      Current Ratio (X)        1.36        0.68        0.62
               21                        Quick Ratio (X)        1.00        0.48        0.44
               22                                    NaN         NaN         NaN         NaN
               23                      Efficiency Ratios         NaN         NaN         NaN
               24           Inventory Turnover Ratio (X)        7.79        6.14        8.62
               25         Dividend Payout Ratio (NP) (%)       38.73       22.25       46.82
               26         Dividend Payout Ratio (CP) (%)       28.94       19.24       34.41
               27           Earnings Retention Ratio (%)       61.27       77.75       53.18
               28      Cash Earnings Retention Ratio (%)       71.06       80.76       65.59
               29               Asset Turnover Ratio (%)       82.47       53.51       85.41
               30                                    NaN         NaN         NaN         NaN
               31                       Valuation Ratios         NaN         NaN         NaN
               32                 Enterprise Value (Cr.)     5400.03     8638.37     6359.97
               33           EV/Net Operating Revenue (X)        1.37        2.14        0.76
               34                          EV/EBITDA (X)        6.67        6.60        6.71
               35    MarketCap/Net Operating Revenue (X)        1.13        1.63        0.40
               36                   Retention Ratios (%)       61.26       77.74       53.17
               37                           Price/BV (X)        1.86        1.84        0.92
               38            Price/Net Operating Revenue        1.13        1.63        0.40
               39                         Earnings Yield        0.10        0.14        0.14
               40                                    NaN         NaN         NaN         NaN

                  Unnamed: 4           Unnamed: 5  Unnamed: 6  Unnamed: 7  Unnamed: 8  \
               0         NaN                  NaN         NaN         NaN         NaN
               1         NaN                  NaN         NaN         NaN         NaN
               2    Pre-Mean  2017-03-10 00:00:00     2011.00     2012.00     2013.00
               3         NaN                  NaN         NaN         NaN         NaN
               4     21.4233                17.46       15.81       16.66       16.55
               5     18.2733                   14       12.58       13.85       14.04
               6       17.16                10.49        8.82        9.55        9.67
               7     13.3867                 8.03        6.45        7.33        7.54
               8     19.2033                10.17        8.61       11.88       12.12
               9     15.2533                 8.21        5.37        7.92        9.60
               10    8.82333                 4.81        4.30        5.43        5.79
               11      26.81                17.87       16.32       23.03       25.25
               12      26.81                17.87       16.32       23.03       25.25
               13    33.5667                25.56       24.05       31.84       33.66
               14     20.071                  NaN         NaN         NaN         NaN
               15        NaN                  NaN         NaN         NaN         NaN
               16   0.703333                 0.69        0.57        0.50        0.46
               17        NaN                  NaN         NaN         NaN         NaN
               18        NaN                  NaN         NaN         NaN         NaN
               19        NaN                  NaN         NaN         NaN         NaN
               20   0.886667                 0.58        1.32        1.15        1.10
               21       0.64                 0.42        0.95        0.78        0.88
               22   0.763333                  NaN         NaN         NaN         NaN
               23        NaN                  NaN         NaN         NaN         NaN
               24    7.51667                 8.85        9.10        6.38        9.20
               25    35.9333                50.35       62.36       43.42       39.60
               26      27.53                35.19       41.56       31.40       29.70
               27    64.0667                49.65       37.64       56.58       60.40
               28      72.47                64.81       58.44       68.60       70.30
               29    73.7967                59.91       66.69       74.08       76.85
               30    46.8856                  NaN         NaN         NaN         NaN
               31        NaN                  NaN         NaN         NaN         NaN
               32    6799.46              10186.8    10532.26    10372.89     9580.48
               33    1.42333                 1.88        1.66        1.30        1.12
               34       6.66                10.78       10.52        7.79        6.79
               35    1.05333                 1.47        1.36        1.10        0.96
               36    64.0567                49.64       37.63       56.57       60.39
               37       1.54                 1.86        1.82        1.78        1.55
               38    1.05333                 1.47        1.36        1.10        0.96
               39   0.126667                 0.05        0.05        0.07        0.08
               40    859.421                  NaN         NaN         NaN         NaN

                  Unnamed: 9  Unnamed: 10  Unnamed: 11  Unnamed: 12  Unnamed: 13  \
               0         NaN          NaN          NaN          NaN          NaN
               1         NaN          NaN          NaN          NaN          NaN
               2   Post-Mean          NaN          NaN          NaN          NaN
               3         NaN          NaN          NaN          NaN          NaN
               4       16.34          NaN          NaN          NaN          NaN
               5       13.49          NaN          NaN          NaN          NaN
               6     9.34667          NaN          NaN          NaN          NaN
               7     7.10667          NaN          NaN          NaN          NaN
               8       10.87          NaN          NaN          NaN          NaN
               9        7.63          NaN          NaN          NaN          NaN
               10    5.17333          NaN          NaN          NaN          NaN
               11    21.5333          NaN          NaN          NaN          NaN
               12    21.5333          NaN          NaN          NaN          NaN
               13      29.85          NaN          NaN          NaN          NaN
               14    14.2873          NaN          NaN          NaN          NaN
               15        NaN          NaN          NaN          NaN          NaN
               16       0.51          NaN          NaN          NaN          NaN
               17        NaN          NaN          NaN          NaN          NaN
               18        NaN          NaN          NaN          NaN          NaN
               19        NaN          NaN          NaN          NaN          NaN
               20       1.19          NaN          NaN          NaN          NaN
               21       0.87          NaN          NaN          NaN          NaN
               22       1.03          NaN          NaN          NaN          NaN
               23        NaN          NaN          NaN          NaN          NaN
               24    8.22667          NaN          NaN          NaN          NaN
               25      48.46          NaN          NaN          NaN          NaN
               26      34.22          NaN          NaN          NaN          NaN
               27      51.54          NaN          NaN          NaN          NaN
               28      65.78          NaN          NaN          NaN          NaN
               29      72.54          NaN          NaN          NaN          NaN
               30    46.7944          NaN          NaN          NaN          NaN
               31        NaN          NaN          NaN          NaN          NaN
               32    10161.9          NaN          NaN          NaN          NaN
               33       1.36          NaN          NaN          NaN          NaN
               34    8.36667          NaN          NaN          NaN          NaN
               35       1.14          NaN          NaN          NaN          NaN
               36      51.53          NaN          NaN          NaN          NaN
               37    1.71667          NaN          NaN          NaN          NaN
               38       1.14          NaN          NaN          NaN          NaN
               39  0.0666667          NaN          NaN          NaN          NaN
               40     1278.4          NaN          NaN          NaN          NaN

                   Unnamed: 14  Unnamed: 15  Unnamed: 16  Unnamed: 17  Unnamed: 18  \
               0           NaN          NaN          NaN          NaN          NaN
               1           NaN          NaN          NaN          NaN          NaN
               2           NaN          NaN          NaN          NaN          NaN
               3           NaN          NaN          NaN          NaN          NaN
               4           NaN          NaN          NaN          NaN          NaN
               5           NaN          NaN          NaN          NaN          NaN
               6           NaN          NaN          NaN          NaN          NaN
               7           NaN          NaN          NaN          NaN          NaN
               8           NaN          NaN          NaN          NaN          NaN
               9           NaN          NaN          NaN          NaN          NaN
               10          NaN          NaN          NaN          NaN          NaN
               11          NaN          NaN          NaN          NaN          NaN
               12          NaN          NaN          NaN          NaN          NaN
               13          NaN          NaN          NaN          NaN          NaN
               14          NaN          NaN          NaN          NaN          NaN
               15          NaN          NaN          NaN          NaN          NaN
               16          NaN          NaN          NaN          NaN          NaN
               17          NaN          NaN          NaN          NaN          NaN
               18          NaN          NaN          NaN          NaN          NaN
               19          NaN          NaN          NaN          NaN          NaN
               20          NaN          NaN          NaN          NaN          NaN
               21          NaN          NaN          NaN          NaN          NaN
               22          NaN          NaN          NaN          NaN          NaN
               23          NaN          NaN          NaN          NaN          NaN
               24          NaN          NaN          NaN          NaN          NaN
               25          NaN          NaN          NaN          NaN          NaN
               26          NaN          NaN          NaN          NaN          NaN
               27          NaN          NaN          NaN          NaN          NaN
               28          NaN          NaN          NaN          NaN          NaN
               29          NaN          NaN          NaN          NaN          NaN
               30          NaN          NaN          NaN          NaN          NaN
               31          NaN          NaN          NaN          NaN          NaN
               32          NaN          NaN          NaN          NaN          NaN
               33          NaN          NaN          NaN          NaN          NaN
               34          NaN          NaN          NaN          NaN          NaN
               35          NaN          NaN          NaN          NaN          NaN
               36          NaN          NaN          NaN          NaN          NaN
               37          NaN          NaN          NaN          NaN          NaN
               38          NaN          NaN          NaN          NaN          NaN
               39          NaN          NaN          NaN          NaN          NaN
               40          NaN          NaN          NaN          NaN          NaN

                   Unnamed: 19
               0           NaN
               1           NaN
               2           NaN
               3           NaN
               4           NaN
               5           NaN
               6           NaN
               7           NaN
               8           NaN
               9           NaN
               10          NaN
               11          NaN
               12          NaN
               13          NaN
               14          NaN
               15          NaN
               16          NaN
               17          NaN
               18          NaN
               19          NaN
               20          NaN
               21          NaN
               22          NaN
               23          NaN
               24          NaN
               25          NaN
               26          NaN
               27          NaN
               28          NaN
               29          NaN
               30          NaN
               31          NaN
               32          NaN
               33          NaN
               34          NaN
               35          NaN
               36          NaN
               37          NaN
               38          NaN
               39          NaN
               40          NaN  )]),
 OrderedDict([('Reliance Power',
                  Key Financial Ratios of Reliance Power           Unnamed: 1  \
               0                                     NaN                  NaN
               1                                     NaN  2017-03-07 00:00:00
               2                    Profitability Ratios                  NaN
               3                        PBDIT Margin (%)                24.08
               4                         PBIT Margin (%)                24.08
               5                          PBT Margin (%)                24.08
               6                   Net Profit Margin (%)                 7.19
               7         Return on Networth / Equity (%)                 0.08
               8          Return on Capital Employed (%)                 0.08
               9                    Return on Assets (%)                 0.07
               10                        Basic EPS (Rs.)                 0.01
               11                      Diluted EPS (Rs.)                 0.01
               12                         Cash EPS (Rs.)                 0.01
               13                                    NaN                  NaN
               14                              Leverage                   NaN
               15                  Total Debt/Equity (X)                    0
               16                                    NaN                  NaN
               17                       Liquidity Ratios                  NaN
               18                      Current Ratio (X)                 9.16
               19                        Quick Ratio (X)                 9.16
               20                                    NaN                  NaN
               21                            Efficiency                   NaN
               22         Dividend Payout Ratio (NP) (%)                  NaN
               23         Dividend Payout Ratio (CP) (%)                  NaN
               24           Earnings Retention Ratio (%)                  100
               25      Cash Earnings Retention Ratio (%)                  100
               26               Asset Turnover Ratio (%)                 1.09
               27                                    NaN                  NaN
               28                       Valuation Ratios                  NaN
               29                 Enterprise Value (Cr.)                    0
               30           EV/Net Operating Revenue (X)                    0
               31                          EV/EBITDA (X)                    0
               32    MarketCap/Net Operating Revenue (X)                    0
               33                   Retention Ratios (%)                  100
               34                           Price/BV (X)                    0
               35            Price/Net Operating Revenue                    0
               36                         Earnings Yield                    0

                            Unnamed: 2           Unnamed: 3 Unnamed: 4           Unnamed: 5  \
               0                   NaN                  NaN        NaN                  NaN
               1   2017-03-08 00:00:00  2017-03-09 00:00:00  Pre- Mean  2017-03-10 00:00:00
               2                   NaN                  NaN        NaN                  NaN
               3                     0                    0        NaN              3385.13
               4                     0                    0        NaN              3379.12
               5                     0                    0        NaN              3379.12
               6                     0                    0        NaN              3195.45
               7                  0.69                  1.8        NaN                 1.94
               8                  0.69                  1.8        NaN                 1.94
               9                  0.67                 1.79        NaN                 1.93
               10                 0.42                 1.04        NaN                 1.14
               11                 0.42                 1.04        NaN                 1.14

In [34]:
df_tatachem=pd.concat( sheet_tatachem[frame] for frame in sheet_tatachem.keys())
df_relpow=pd.concat( sheet_relpow[frame] for frame in sheet_relpow.keys())

In [94]:
df_tatachem

,FinRatio,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,2007.00,2008.00,2009.00,Pre-Mean,2017-03-10 00:00:00,2011.00,2012.00,2013.00,Post-Mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Profitability Ratios,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,PBDIT Margin (%),20.52,32.42,11.33,21.4233,17.46,15.81,16.66,16.55,16.34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,PBIT Margin (%),16.71,28.73,9.38,18.2733,14,12.58,13.85,14.04,13.49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,PBT Margin (%),15.63,28.21,7.64,17.16,10.49,8.82,9.55,9.67,9.34667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Net Profit Margin (%),11.25,23.51,5.40,13.3867,8.03,6.45,7.33,7.54,7.10667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Return on Networth / Equity (%),18.56,26.57,12.48,19.2033,10.17,8.61,11.88,12.12,10.87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Return on Capital Employed (%),13.08,22.61,10.07,15.2533,8.21,5.37,7.92,9.60,7.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Return on Assets (%),9.28,12.58,4.61,8.82333,4.81,4.30,5.43,5.79,5.17333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Basic EPS (Rs.),20.65,40.56,19.22,26.81,17.87,16.32,23.03,25.25,21.5333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Diluted EPS (Rs.),20.65,40.56,19.22,26.81,17.87,16.32,23.03,25.25,21.5333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Cash EPS (Rs.),27.63,46.92,26.15,33.5667,25.56,24.05,31.84,33.66,29.85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,20.071,NaN,NaN,NaN,NaN,14.2873,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Leverage Ratios,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Total Debt/Equity (X),0.44,0.66,1.01,0.703333,0.69,0.57,0.50,0.46,0.51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Liquidity Ratios,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Current Ratio (X),1.36,0.68,0.62,0.886667,0.58,1.32,1.15,1.10,1.19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Quick Ratio (X),1.00,0.48,0.44,0.64,0.42,0.95,0.78,0.88,0.87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,0.763333,NaN,NaN,NaN,NaN,1.03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Efficiency Ratios,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Inventory Turnover Ratio (X),7.79,6.14,8.62,7.51667,8.85,9.10,6.38,9.20,8.22667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Dividend Payout Ratio (NP) (%),38.73,22.25,46.82,35.9333,50.35,62.36,43.42,39.60,48.46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Dividend Payout Ratio (CP) (%),28.94,19.24,34.41,27.53,35.19,41.56,31.40,29.70,34.22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Earnings Retention Ratio (%),61.27,77.75,53.18,64.0667,49.65,37.64,56.58,60.40,51.54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Cash Earnings Retention Ratio (%),71.06,80.76,65.59,72.47,64.81,58.44,68.60,70.30,65.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Asset Turnover Ratio (%),82.47,53.51,85.41,73.7967,59.91,66.69,74.08,76.85,72.54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,46.8856,NaN,NaN,NaN,NaN,46.7944,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Valuation Ratios,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Enterprise Value (Cr.),5400.03,8638.37,6359.97,6799.46,10186.8,10532.26,10372.89,9580.48,10161.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,EV/Net Operating Revenue (X),1.37,2.14,0.76,1.42333,1.88,1.66,1.30,1.12,1.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,EV/EBITDA (X),6.67,6.60,6.71,6.66,10.78,10.52,7.79,6.79,8.36667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,MarketCap/Net Operating Revenue (X),1.13,1.63,0.40,1.05333,1.47,1.36,1.10,0.96,1.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Retention Ratios (%),61.26,77.74,53.17,64.0567,49.64,37.63,56.57,60.39,51.53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,Price/BV (X),1.86,1.84,0.92,1.54,1.86,1.82,1.78,1.55,1.71667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Price/Net Operating Revenue,1.13,1.63,0.40,1.05333,1.47,1.36,1.10,0.96,1.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Earnings Yield,0.10,0.14,0.14,0.126667,0.05,0.05,0.07,0.08,0.0666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,859.421,NaN,NaN,NaN,NaN,1278.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [89]:

df_tatachem[df_tatachem['Key Financial Ratios of Tata Chemicals'].isnull()]

KeyError: 'Key Financial Ratios of Tata Chemicals'

In [48]:
for col in df_tatachem.columns: 
    print(col)

Key Financial Ratios of Tata Chemicals
Unnamed: 1
Unnamed: 2
Unnamed: 3
Unnamed: 4
Unnamed: 5
Unnamed: 6
Unnamed: 7
Unnamed: 8
Unnamed: 9
Unnamed: 10
Unnamed: 11
Unnamed: 12
Unnamed: 13
Unnamed: 14
Unnamed: 15
Unnamed: 16
Unnamed: 17
Unnamed: 18
Unnamed: 19

In [95]:
df_tatachem.rename(columns={ df_tatachem.columns[0]: "FinRatio" }, inplace = True)

In [54]:
df_tatachem[df_tatachem['FinRatio'].isnull()]

,FinRatio,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,2007.0,2008.0,2009.0,Pre-Mean,2017-03-10 00:00:00,2011.0,2012.0,2013.0,Post-Mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,20.071,NaN,NaN,NaN,NaN,14.2873,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,0.763333,NaN,NaN,NaN,NaN,1.03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,46.8856,NaN,NaN,NaN,NaN,46.7944,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,859.421,NaN,NaN,NaN,NaN,1278.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_tatachem.insert(0, 'Company', )

In [96]:
df_tatachem

,FinRatio,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,2007.00,2008.00,2009.00,Pre-Mean,2017-03-10 00:00:00,2011.00,2012.00,2013.00,Post-Mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Profitability Ratios,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,PBDIT Margin (%),20.52,32.42,11.33,21.4233,17.46,15.81,16.66,16.55,16.34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,PBIT Margin (%),16.71,28.73,9.38,18.2733,14,12.58,13.85,14.04,13.49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,PBT Margin (%),15.63,28.21,7.64,17.16,10.49,8.82,9.55,9.67,9.34667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Net Profit Margin (%),11.25,23.51,5.40,13.3867,8.03,6.45,7.33,7.54,7.10667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Return on Networth / Equity (%),18.56,26.57,12.48,19.2033,10.17,8.61,11.88,12.12,10.87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Return on Capital Employed (%),13.08,22.61,10.07,15.2533,8.21,5.37,7.92,9.60,7.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Return on Assets (%),9.28,12.58,4.61,8.82333,4.81,4.30,5.43,5.79,5.17333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Basic EPS (Rs.),20.65,40.56,19.22,26.81,17.87,16.32,23.03,25.25,21.5333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Diluted EPS (Rs.),20.65,40.56,19.22,26.81,17.87,16.32,23.03,25.25,21.5333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Cash EPS (Rs.),27.63,46.92,26.15,33.5667,25.56,24.05,31.84,33.66,29.85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,20.071,NaN,NaN,NaN,NaN,14.2873,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Leverage Ratios,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Total Debt/Equity (X),0.44,0.66,1.01,0.703333,0.69,0.57,0.50,0.46,0.51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Liquidity Ratios,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Current Ratio (X),1.36,0.68,0.62,0.886667,0.58,1.32,1.15,1.10,1.19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Quick Ratio (X),1.00,0.48,0.44,0.64,0.42,0.95,0.78,0.88,0.87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,0.763333,NaN,NaN,NaN,NaN,1.03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Efficiency Ratios,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Inventory Turnover Ratio (X),7.79,6.14,8.62,7.51667,8.85,9.10,6.38,9.20,8.22667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Dividend Payout Ratio (NP) (%),38.73,22.25,46.82,35.9333,50.35,62.36,43.42,39.60,48.46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Dividend Payout Ratio (CP) (%),28.94,19.24,34.41,27.53,35.19,41.56,31.40,29.70,34.22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Earnings Retention Ratio (%),61.27,77.75,53.18,64.0667,49.65,37.64,56.58,60.40,51.54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Cash Earnings Retention Ratio (%),71.06,80.76,65.59,72.47,64.81,58.44,68.60,70.30,65.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Asset Turnover Ratio (%),82.47,53.51,85.41,73.7967,59.91,66.69,74.08,76.85,72.54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,46.8856,NaN,NaN,NaN,NaN,46.7944,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Valuation Ratios,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Enterprise Value (Cr.),5400.03,8638.37,6359.97,6799.46,10186.8,10532.26,10372.89,9580.48,10161.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,EV/Net Operating Revenue (X),1.37,2.14,0.76,1.42333,1.88,1.66,1.30,1.12,1.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,EV/EBITDA (X),6.67,6.60,6.71,6.66,10.78,10.52,7.79,6.79,8.36667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,MarketCap/Net Operating Revenue (X),1.13,1.63,0.40,1.05333,1.47,1.36,1.10,0.96,1.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Retention Ratios (%),61.26,77.74,53.17,64.0567,49.64,37.63,56.57,60.39,51.53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,Price/BV (X),1.86,1.84,0.92,1.54,1.86,1.82,1.78,1.55,1.71667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Price/Net Operating Revenue,1.13,1.63,0.40,1.05333,1.47,1.36,1.10,0.96,1.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Earnings Yield,0.10,0.14,0.14,0.126667,0.05,0.05,0.07,0.08,0.0666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,859.421,NaN,NaN,NaN,NaN,1278.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [98]:
df_tatachem <- df_tatachem[colSums(is.na(df_tatachem))<nrow(df_tatachem)]

SyntaxError: invalid syntax (<ipython-input-98-5b10b6f2ef3e>, line 1)

In [110]:
df_tatachem.isna().sum()=len(df_tatachem)

FinRatio        9
Unnamed: 1     13
Unnamed: 2     13
Unnamed: 3     13
Unnamed: 4      9
Unnamed: 5     13
Unnamed: 6     13
Unnamed: 7     13
Unnamed: 8     13
Unnamed: 9      9
Unnamed: 10    41
Unnamed: 11    41
Unnamed: 12    41
Unnamed: 13    41
Unnamed: 14    41
Unnamed: 15    41
Unnamed: 16    41
Unnamed: 17    41
Unnamed: 18    41
Unnamed: 19    41
dtype: int64

In [114]:
df_tatachem1 = df_tatachem.loc[:, (df_tatachem.isnull().sum(axis=0) < len(df_tatachem))]

In [115]:
df_tatachem1

,FinRatio,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,2007.00,2008.00,2009.00,Pre-Mean,2017-03-10 00:00:00,2011.00,2012.00,2013.00,Post-Mean
3,Profitability Ratios,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,PBDIT Margin (%),20.52,32.42,11.33,21.4233,17.46,15.81,16.66,16.55,16.34
5,PBIT Margin (%),16.71,28.73,9.38,18.2733,14,12.58,13.85,14.04,13.49
6,PBT Margin (%),15.63,28.21,7.64,17.16,10.49,8.82,9.55,9.67,9.34667
7,Net Profit Margin (%),11.25,23.51,5.40,13.3867,8.03,6.45,7.33,7.54,7.10667
8,Return on Networth / Equity (%),18.56,26.57,12.48,19.2033,10.17,8.61,11.88,12.12,10.87
9,Return on Capital Employed (%),13.08,22.61,10.07,15.2533,8.21,5.37,7.92,9.60,7.63
10,Return on Assets (%),9.28,12.58,4.61,8.82333,4.81,4.30,5.43,5.79,5.17333
11,Basic EPS (Rs.),20.65,40.56,19.22,26.81,17.87,16.32,23.03,25.25,21.5333
12,Diluted EPS (Rs.),20.65,40.56,19.22,26.81,17.87,16.32,23.03,25.25,21.5333
13,Cash EPS (Rs.),27.63,46.92,26.15,33.5667,25.56,24.05,31.84,33.66,29.85
14,NaN,NaN,NaN,NaN,20.071,NaN,NaN,NaN,NaN,14.2873
15,Leverage Ratios,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Total Debt/Equity (X),0.44,0.66,1.01,0.703333,0.69,0.57,0.50,0.46,0.51
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Liquidity Ratios,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Current Ratio (X),1.36,0.68,0.62,0.886667,0.58,1.32,1.15,1.10,1.19
21,Quick Ratio (X),1.00,0.48,0.44,0.64,0.42,0.95,0.78,0.88,0.87
22,NaN,NaN,NaN,NaN,0.763333,NaN,NaN,NaN,NaN,1.03
23,Efficiency Ratios,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Inventory Turnover Ratio (X),7.79,6.14,8.62,7.51667,8.85,9.10,6.38,9.20,8.22667
25,Dividend Payout Ratio (NP) (%),38.73,22.25,46.82,35.9333,50.35,62.36,43.42,39.60,48.46
26,Dividend Payout Ratio (CP) (%),28.94,19.24,34.41,27.53,35.19,41.56,31.40,29.70,34.22
27,Earnings Retention Ratio (%),61.27,77.75,53.18,64.0667,49.65,37.64,56.58,60.40,51.54
28,Cash Earnings Retention Ratio (%),71.06,80.76,65.59,72.47,64.81,58.44,68.60,70.30,65.78
29,Asset Turnover Ratio (%),82.47,53.51,85.41,73.7967,59.91,66.69,74.08,76.85,72.54
30,NaN,NaN,NaN,NaN,46.8856,NaN,NaN,NaN,NaN,46.7944
31,Valuation Ratios,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Enterprise Value (Cr.),5400.03,8638.37,6359.97,6799.46,10186.8,10532.26,10372.89,9580.48,10161.9
33,EV/Net Operating Revenue (X),1.37,2.14,0.76,1.42333,1.88,1.66,1.30,1.12,1.36
34,EV/EBITDA (X),6.67,6.60,6.71,6.66,10.78,10.52,7.79,6.79,8.36667
35,MarketCap/Net Operating Revenue (X),1.13,1.63,0.40,1.05333,1.47,1.36,1.10,0.96,1.14
36,Retention Ratios (%),61.26,77.74,53.17,64.0567,49.64,37.63,56.57,60.39,51.53
37,Price/BV (X),1.86,1.84,0.92,1.54,1.86,1.82,1.78,1.55,1.71667
38,Price/Net Operating Revenue,1.13,1.63,0.40,1.05333,1.47,1.36,1.10,0.96,1.14
39,Earnings Yield,0.10,0.14,0.14,0.126667,0.05,0.05,0.07,0.08,0.0666667
40,NaN,NaN,NaN,NaN,859.421,NaN,NaN,NaN,NaN,1278.4